stages:
  - notify

notify_telegram:
  stage: notify
  script:
    - >
      if [[ "$CI_COMMIT_MESSAGE" == *"Merge branch"* || "$CI_COMMIT_MESSAGE" == *"Merge remote-tracking branch"* ]]; then
        EVENT_TYPE="Merge";
      else
        EVENT_TYPE="Push";
      fi

      COMMIT_ID="$CI_COMMIT_SHORT_SHA"
      COMMIT_MSG=$(echo "$CI_COMMIT_MESSAGE" | sed 's/"/\\"/g')
      PROJECT_NAME="$CI_PROJECT_NAME"

      MESSAGE="🚀<b>New $EVENT_TYPE</b>\n<b>Project</b>     : $PROJECT_NAME\n<b>Commit ID</b>   : <code>$COMMIT_ID</code>\n<b>Commit Msg</b>  : $COMMIT_MSG"

      curl -s -X POST -H 'Content-Type: application/json' \
        -d "{\"chat_id\": \"-1002336929122_4\", \"message_thread_id\": 4, \"text\": \"$MESSAGE\", \"parse_mode\": \"HTML\"}" \
        https://api.telegram.org/bot7494741116:AAFCtf_b4j5XunhQ_v524lT0gyqDpMba_ew/sendMessage
  only:
    - branches
  when: on_success
